name: Deploy

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - uses: actions/checkout@v1
      - name: Use Node.js 18.19.0
        uses: actions/setup-node@v1
        with:
          node-version: 18.19.0
      - name: Install dependencies
        run: npm install
      - name: Combine strings
        uses: michpohl/action-concatenate-strings@v1
        with:
          first: ${{ secrets.PUBLIC_URL }}
          second: ${GITHUB_REF##*/}
          separator: '/'
          output-var-name: 'DEPLOY_URL'
      - name: Build
        run: node ./node_modules/@angular/cli/bin/ng build --deploy-url ${DEPLOY_URL}
        env:
          HTTPS: 'true'
          BASE_URL: ${{ secrets.BASE_URL }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: dev
