name: Deploy

on: [workflow_dispatch]
env: 
  PUBLIC_URL: ${{ github.ref == 'refs/heads/main' 
    && format('{0}{1}', secrets.PUBLIC_URL, 'prod/')
    || format('{0}/{1}', secrets.PUBLIC_URL, 'dev/') }}

  BASE_URL: ${{ github.ref == 'refs/heads/main' 
    && format('{0}{1}', secrets.BASE_URL, 'prod/')
    || format('{0}{1}', secrets.BASE_URL, 'dev/') }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - uses: actions/checkout@v1
      - name: Use Node.js 18.19.0
        uses: actions/setup-node@v1
        with:
          node-version: 18.19.0
      - name: Install dependencies
        run: npm install
     
      - name: Build
        run: node ./node_modules/@angular/cli/bin/ng build --deploy-url ${{ env.PUBLIC_URL }} --base-href https://bivhunter.github.io/my-app/dev
        env:
          HTTPS: 'true'
          BASE_URL: ${{ env.BASE_URL }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: dev
